### ISSUE TITLE
Consider standard ontology/CURIE representation 

### ISSUE THREAD

**Issue by mellybelly** [ga4gh-rnaseq/schema#57]
for things like phenotype or tissue
e.g. 
ontology term ID (CURIE)
Ontology term Label 

you could consider Uberon for tissues
HPO or NCIT for phenotypes

For organisms consider NCBItaxon (same - CURIE + label)

**Comment by mbaudis** [comment]
OntologyClass: https://schemablocks.org/schemas/ga4gh/OntologyClass.html => Phenopackets aligned, overarching use.

**Comment by mellybelly** [comment]
+1 @mbaudis, this is great!

**Comment by mbaudis** [comment]
... there are missing backlinks (& objects) right now due to the "dynamic alignment" with a) Phenopackets & b) emerging versions of JSON Schema, but I think we're getting there at [{S}[B]](http://schemablocks.org). So it would be great to have [rnaseq](https://github.com/ga4gh-rnaseq/schema/blob/master/rnaget.md) looking at it/aligning/contributing ...

**Comment by julesjacobsen** [comment]
Sorry @mellybelly, i don't understand what you're suggesting. Can you gave an example of what we're doing now and how you think it could be improved?

**Comment by mbaudis** [comment]
@julesjacobsen This is suggesting that "rnaseq" should use the `id` + `label` constructs, like Phenopackets. This can become relevant for search/filtering, AFAIK.

**Comment by julesjacobsen** [comment]
Aaaaaahhh!!! I'm sorry - I have been an idiot and though this was an issue in the phenopacket-schema repo! These issue trackers all look the same... Please ignore my last post, but do follow the links!

**Comment by mbaudis** [comment]
@julesjacobsen +1 for 
> These issue trackers all look the same.

Not commenting otherwise :-)
