### ISSUE TITLE
why does expressions/tickets only return 1 ticket based on the spec

### ISSUE THREAD

**Issue by haoyuanli** [ga4gh-rnaseq/schema#76]
it used to be a list of tickets/files.

what happens if your search filters have more than 1 valid tickets?

now:
![image](https://user-images.githubusercontent.com/18109953/70956395-bffc8700-2028-11ea-90c7-4cff778e4b67.png)

before:
![image](https://user-images.githubusercontent.com/18109953/70956412-cbe84900-2028-11ea-98c2-79005a3f1630.png)

**Comment by jb-adams** [comment]
hi @haoyuanli, this is a structural change that was made to the API schema. Any request for a matrix (expression or continuous, as ticket or bytes) will result in only 1 matrix being made available to the client. Conceptually, `/expressions/tickets` now lets the client request all data that matches specified filters, rather than searching for all expression ids matching the filters (the old model).

So, if the client specifies filters that correspond to 2 expression IDs/files on the backend, the matrix contents from each file should be dynamically aggregated into a single, combined matrix. Row and column filtering is applied to all expression files, such that the final combined matrix contains only the specified features and samples.

**Comment by haoyuanli** [comment]
Oh ok, that makes sense. I will think about it. Thanks.

On an unrelated note, the tests for a ticket endpoint is currently failing

```
Content Test Case: Single Expression Ticket - Expression Value 1 - FAILED

error message: Error parsing expression json and download url: Unable to create file (unable to open file: name = 'single_expression_ticket_content_test.loom', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)
```

Does this mean that the test suite is able to read the json response of the `tickets` endpoint and locate the `url`, but is unable to download the file based on the url? Thanks

**Comment by jb-adams** [comment]
hi @haoyuanli, yes that is likely the case. The compliance app is trying to download the matrix via the url in the ticket and save it locally, but is unable to do so. Can you manually try to download the matrix from the ticket your API returns?

**Comment by haoyuanli** [comment]
> hi @haoyuanli, yes that is likely the case. The compliance app is trying to download the matrix via the url in the ticket and save it locally, but is unable to do so. Can you manually try to download the matrix from the ticket your API returns?

I am unable to downlowd the matrix from the URL provided; it is likely something that goes wrong at the API gateway (authorization level) instead of the API implementation itself - but this info is good to know!

Thanks

**Comment by haoyuanli** [comment]
> hi @haoyuanli, yes that is likely the case. The compliance app is trying to download the matrix via the url in the ticket and save it locally, but is unable to do so. Can you manually try to download the matrix from the ticket your API returns?

Also, were you given any special token to test our the candig rnaget API? Thanks

**Comment by jb-adams** [comment]
@haoyuanli yes Adam gave me an API token

**Comment by haoyuanli** [comment]
> @haoyuanli yes Adam gave me an API token

@jb-adams  i have just updated the implementation - it should work now

**Comment by jb-adams** [comment]
looks great @haoyuanli, you are passing all tests! Can I close this?

**Comment by haoyuanli** [comment]
sure, thanks
